name: Build

on:
  push:
    branches:
      - master
      - branch-*
      - dogfood-*
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Required permissions for Vault OIDC and repo operations
permissions:
  id-token: write
  contents: write

env:
  CACHE_BACKEND: s3

jobs:
  build:
    runs-on: github-ubuntu-latest-s
    name: Build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@c0b8518a9f5e56c720e9545c993b77ff15dc7b27 # v3.0.2
        with:
          version: 2025.9.15
      - uses: SonarSource/ci-github-actions/build-maven@c15f3733837c5ebd0f04a676feb1e18fae147cd5 # 1.3.27
        with:
          maven-args: -Dmaven.test.skip=true -Dsonar.skip=true
          deploy-pull-request: true
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer

  qa-linux:
    needs: [ build ]
    runs-on: github-ubuntu-latest-s
    name: QA Linux
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@c0b8518a9f5e56c720e9545c993b77ff15dc7b27 # v3.0.2
        with:
          version: 2025.9.15
      - uses: SonarSource/ci-github-actions/build-maven@c15f3733837c5ebd0f04a676feb1e18fae147cd5 # 1.3.27
        with:
          maven-args: -Dcommercial -Dmaven.install.skip=true -Dmaven.deploy.skip=true -P-deploy-sonarsource,-release,-sign
          artifactory-deployer-role: qa-deployer
          artifactory-reader-role: private-reader
      - name: Generate test report
        uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
        if: ${{ !cancelled() }}
        with:
          name: QA Linux Test Report
          reporter: java-junit
          path: '**/target/surefire-reports/TEST-*.xml'
          list-suites: failed
          list-tests: failed

  qa-windows:
    needs: [ build ]
    runs-on: github-windows-latest-s
    name: QA Windows
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@c0b8518a9f5e56c720e9545c993b77ff15dc7b27 # v3.0.2
        with:
          version: 2025.9.15
      - uses: SonarSource/ci-github-actions/build-maven@c15f3733837c5ebd0f04a676feb1e18fae147cd5 # 1.3.27
        with:
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          sonar-platform: none
          maven-args: -B -e -V -Dcommercial -Dmaven.test.redirectTestOutputToFile=false
      - name: Generate test report
        uses: dorny/test-reporter@3d76b34a4535afbd0600d347b09a6ee5deb3ed7f # v2.6.0
        if: ${{ !cancelled() }}
        with:
          name: QA Linux Test Report
          reporter: java-junit
          path: '**/target/surefire-reports/TEST-*.xml'
          list-suites: failed
          list-tests: failed

  promote:
    needs: [ build, qa-linux, qa-windows ]
    runs-on: github-ubuntu-latest-s
    name: Promote
    steps:
      - uses: SonarSource/ci-github-actions/promote@c15f3733837c5ebd0f04a676feb1e18fae147cd5 # 1.3.27
        with:
          promote-pull-request: true
