name: sonar-release
# This workflow is triggered when publishing a new GitHub release
on:
  release:
    types:
      - published

jobs:
  release:
    permissions:
      id-token: write
      contents: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@582722e3a48525082240d4eaf69461ce158551da
    with:
      publishToBinaries: false
      mavenCentralSync: true
      slackChannel: team-sonarlint-vscode
