name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: github-ubuntu-latest-s
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2025.9.12
      - uses: SonarSource/ci-github-actions/build-maven@v1
        with:
          run-shadow-scans: true
          artifactory-deployer-role: qa-deployer
          maven-args: -release,-sign -Dcommercial -Dmaven.install.skip=true
          artifactory-reader-role: private-reader
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.sonarlint.ls:sonarlint-language-server"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.sonarlint.ls:sonarlint-language-server"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.sonarlint.ls:sonarlint-language-server"
          shadow2_platform: "SQC-US"