name: Shadow scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  CACHE_BACKEND: s3

jobs:
  scan:
    runs-on: github-ubuntu-latest-s
    name: Scan on shadow platforms
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          version: 2026.4.11
      - uses: SonarSource/ci-github-actions/build-maven@657e44543f55422ffd28b91d62fe5386f07d6030 # 1.6.0
        with:
          run-shadow-scans: true
          artifactory-deployer-role: qa-deployer
          maven-args: -P-release,-sign -Dmaven.install.skip=true
          artifactory-reader-role: private-reader
      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@03e023516511b1c9da325ad104c2290e3b91688c # 1.1.0
        with:
          primary_project_key: "org.sonarsource.sonarlint.ls:sonarlint-language-server"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.sonarlint.ls:sonarlint-language-server"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.sonarlint.ls:sonarlint-language-server"
          shadow2_platform: "SQC-US"
